apiVersion: v1
kind: ConfigMap
metadata:
  name: site-config
  labels:
    {{- include "example-app.labels" . | nindent 4 }}
data:
  example-site.conf: |
    server {
        listen       8080 default_server;
        listen  [::]:8080 default_server;
        server_name  {{ .Values.siteConfig.serverName }};

        location / {
            root   {{ .Values.siteConfig.root }};
            index  index.html index.htm;
        }
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   {{ .Values.siteConfig.root }};
        }
    }
