apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    {{- include "example-app.labels" . | nindent 4 }}
    {{- range $k, $v := .Values.service.labels }}
    {{ $k }}: {{ $v }}
    {{- end }}
spec:
  selector:
    {{- include "example-app.labels" . | nindent 4 }}
  ports:
  {{- range $key, $port := .Values.service.ports }}
    - name: {{ $key }}
      protocol: TCP
      port: {{ $port.port }}
      targetPort: {{ $port.targetPort }}
  {{- end }}
